### ISSUE TITLE
Garbage count printed when using Sylvan with weighted counting and multiple precision both set to true

### ISSUE THREAD

**Issue by allrtaken** [vardigroup/DPMC#2]
Please see attached input file and output. The "c s exact arb float 12.6188" line is the correct count, but arb frac line is garbage.

[weighted_blasted.cnf.txt](https://github.com/vardigroup/DPMC/files/6881545/weighted_blasted.cnf.txt)
[garbage_count.txt](https://github.com/vardigroup/DPMC/files/6881539/garbage_count.txt)

**Comment by vuphan314** [comment]
Undocumented format for model-counting competition:
```
c s exact arb frac $numer/$denomin
```
