### ISSUE TITLE
static binary of ProCount

### ISSUE THREAD

**Issue by mahi045** [vardigroup/DPMC#3]
Dear @vuphan314 @Kasekopf 
Could you please share a static binary of [ProCount](https://github.com/vardigroup/DPMC/tree/procount)? It would be helpful for my research.
Thanks.

**Comment by vuphan314** [comment]
@mahi045 An asset of this [release](https://github.com/vardigroup/DPMC/releases/tag/mc-2021) is `dpmc.zip`, which contains binaries. Does that work for you?

**Comment by vuphan314** [comment]
An asset of this [pre-release](https://github.com/vardigroup/DPMC/releases/tag/mc-2022) is `dpmc.zip`, which contains statically linked binaries, built with `g++ 11.2`.

There is little I can do about the `kernel too old` error. You can build from the source or ask your cluster admin.
