### ISSUE TITLE
Error: Unable to run tree decomposition solver.

### ISSUE THREAD

**Issue by mahi045** [vardigroup/DPMC#4]
I built `lg` (without singularity); I also have `flow_cutter_pace17` as a tree decomposition solver. I used the following command to run `lg`:
```
./lg "flow_cutter_pace17 -s 1234567 -p 100" < phi.wpcnf
```
Note that `lg` and `flow_cutter_pace17` are in the same directory. But I got the following error:
```
Error: Unable to run tree decomposition solver.
```
Should I build `lg` **using singularity** to avoid the error?

**Comment by vuphan314** [comment]
Your binaries were built for Linux 2.6.18, so this command fails:
```bash
./lg "flow_cutter_pace17 -p 100" < phi.cnf
```
```
Error: Unable to run tree decomposition solver.
```

This command works (`./` added):
```bash
./lg "./flow_cutter_pace17 -p 100" < phi.cnf
```
```
c pid 472667
c min degree heuristic
c outputing bagsize 2
p jt 6 5 10
6 1 e 2 4
7 4 5 e 3 5
8 2 e 6
9 7 8 3 e 1
10 6 9 e
c joinTreeWidth 2
c seconds 0.0003663
=
c status 2 1657600312459
c min shortcut heuristic
c run with 0.0/0.1/0.2 min balance and node_min_expansion in endless loop with varying seed
^C
```

My binaries were built for Linux 3.2.0, so both commands work.

Is this issue resolved?
