### ISSUE TITLE
Weights must be in ]0, 1[

### ISSUE THREAD

**Issue by AlexandreDubray** [vardigroup/DPMC#8]
Hi,

for the weighted version of DMC, it seems that the weights of the literals must be in the interval ]0,1[.
However for some problems, it might be the case that the weights of a pair of (mutually exclusive) literals are 0 and 1.

A possible alternative would be to set the weights to something like `0.99999999` and `0.00000001` but this would still give a small imprecision in the result.

Why is it not possible to set weights to 0 and 1? Are they ways around that constraint ?

Cheers

**Comment by vuphan314** [comment]
I will see whether literal weights 0 and 1 can be supported.

Meanwhile, can you give a concrete example in which literal weights 0 and 1 are needed? A paper reference with that example would be nice.

**Comment by AlexandreDubray** [comment]
Thansk for looking into it.

The use case I've got is for modelling Bayesian Networks. In some cases (see for example [this one](https://www.bnlearn.com/bnrepository/discrete-small.html#asia) ) there are some variable that have 1.0 and 0.0 probabilities in their probability table (variable "either" in the previous network).

In the modelling I'm working on (for which I do not have a reference to the paper, sorry. But hopefully soon enough), there is one literal per entry, and its weight is the probability of the entry.

While it may be possible to bypass the issue of 0.0 and 1.0 weights with certain clauses, I find this solution less elegant. However, there may be technical reasons why 0.0 and 1.0 weights are not allowed.

**Comment by vuphan314** [comment]
@AlexandreDubray

I made DPMC accept literal weights 0 and 1 in commit https://github.com/vardigroup/DPMC/commit/07060bab154c11a3e4c7fe1465a4e789409ed99d, which has been merged to the master branch.

If the update works for you, please close this issue. Thank you.

**Comment by AlexandreDubray** [comment]
Works like a charm, thanks.
